// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               unknown
// source: stats.proto

/* eslint-disable */

export const protobufPackage = 'model';

/**
 * SchedStat represents the raw metrics from /proc/[pid]/schedstat
 *  https://www.kernel.org/doc/Documentation/scheduler/sched-stats.txt
 */
export interface SchedStat {
	/** total time spent executing on the CPU (nanoseconds) */
	cpuTime: string;
	/** total time spent waiting in the run-queue (nanoseconds) */
	runDelay: string;
	/** number of timeslices run on this CPU */
	pCount: string;
}
