// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stats.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SchedStat represents the raw metrics from /proc/[pid]/schedstat
//
//	https://www.kernel.org/doc/Documentation/scheduler/sched-stats.txt
type SchedStat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total time spent executing on the CPU (nanoseconds)
	CpuTime int64 `protobuf:"varint,1,opt,name=cpu_time,json=cpuTime,proto3" json:"cpu_time,omitempty"`
	// total time spent waiting in the run-queue (nanoseconds)
	RunDelay int64 `protobuf:"varint,2,opt,name=run_delay,json=runDelay,proto3" json:"run_delay,omitempty"`
	// number of timeslices run on this CPU
	PCount        int64 `protobuf:"varint,3,opt,name=p_count,json=pCount,proto3" json:"p_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedStat) Reset() {
	*x = SchedStat{}
	mi := &file_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedStat) ProtoMessage() {}

func (x *SchedStat) ProtoReflect() protoreflect.Message {
	mi := &file_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedStat.ProtoReflect.Descriptor instead.
func (*SchedStat) Descriptor() ([]byte, []int) {
	return file_stats_proto_rawDescGZIP(), []int{0}
}

func (x *SchedStat) GetCpuTime() int64 {
	if x != nil {
		return x.CpuTime
	}
	return 0
}

func (x *SchedStat) GetRunDelay() int64 {
	if x != nil {
		return x.RunDelay
	}
	return 0
}

func (x *SchedStat) GetPCount() int64 {
	if x != nil {
		return x.PCount
	}
	return 0
}

var File_stats_proto protoreflect.FileDescriptor

const file_stats_proto_rawDesc = "" +
	"\n" +
	"\vstats.proto\x12\x05model\"\\\n" +
	"\tSchedStat\x12\x19\n" +
	"\bcpu_time\x18\x01 \x01(\x03R\acpuTime\x12\x1b\n" +
	"\trun_delay\x18\x02 \x01(\x03R\brunDelay\x12\x17\n" +
	"\ap_count\x18\x03 \x01(\x03R\x06pCountBz\n" +
	"\tcom.modelB\n" +
	"StatsProtoP\x01Z-github.com/ryanjmack/forensic-trace/pkg/model\xa2\x02\x03MXX\xaa\x02\x05Model\xca\x02\x05Model\xe2\x02\x11Model\\GPBMetadata\xea\x02\x05Modelb\x06proto3"

var (
	file_stats_proto_rawDescOnce sync.Once
	file_stats_proto_rawDescData []byte
)

func file_stats_proto_rawDescGZIP() []byte {
	file_stats_proto_rawDescOnce.Do(func() {
		file_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)))
	})
	return file_stats_proto_rawDescData
}

var file_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stats_proto_goTypes = []any{
	(*SchedStat)(nil), // 0: model.SchedStat
}
var file_stats_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stats_proto_init() }
func file_stats_proto_init() {
	if File_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stats_proto_rawDesc), len(file_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stats_proto_goTypes,
		DependencyIndexes: file_stats_proto_depIdxs,
		MessageInfos:      file_stats_proto_msgTypes,
	}.Build()
	File_stats_proto = out.File
	file_stats_proto_goTypes = nil
	file_stats_proto_depIdxs = nil
}
